version: '2'
volumes:
  fs_database:
services:
  database:
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - 'fs_database:/var/lib/postgresql/data'
    ports:
      - '8432:5432'
